/*
==============================================================================

  This file was auto-generated by the GINnJUCE Transpiler. You're welcome!

==============================================================================
*/

#ifndef MAINLAYOUT_H_INCLUDED
#define MAINLAYOUT_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "Controls.h"
#include "PresetMenu.h"

class MainLayout :
public Component
{
public:
   MainLayout();
   ~MainLayout();

   void paint(Graphics&) override;
   void resized() override;

   void initializeText();
   void initializePaths();

private:
   Controls controls;
   PresetMenu presetMenu;
   TextEditor title;
   TextEditor author;
   DrawablePath background;
   
   JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MainLayout)
};

#endif // MAINLAYOUT_H_INCLUDED
