/*
==============================================================================

  This file was auto-generated by the GINnJUCE Transpiler. You're welcome!

==============================================================================
*/

#include "PresetMenu.h"

PresetMenu::PresetMenu() {
   initializeText();
   initializePaths();
   addAndMakeVisible(fill);
   addAndMakeVisible(preset);
   
}

PresetMenu::~PresetMenu() {

}

void PresetMenu::paint(Graphics& g) {

}

void PresetMenu::resized() {
   fill.setBounds(0, 0, 202, 25);
   preset.setBounds(69, 5, 65, 17);
}

void PresetMenu::initializeText() {
   // Text initialization for preset
   Font presetFont(String("Raleway"), String("Raleway-Regular"), 14.0f);
   presetFont.setHorizontalScale(1.0f);
   preset.setFont(presetFont);
   preset.setColour(TextEditor::ColourIds::backgroundColourId, Colour(0x00000000));
   preset.setColour(TextEditor::ColourIds::textColourId, Colour(0xfff1f1fa));
   preset.setColour(TextEditor::ColourIds::outlineColourId , Colour(0x00000000));
   preset.setColour(TextEditor::ColourIds::focusedOutlineColourId , Colour(0x00000000));
   preset.setColour(TextEditor::ColourIds::shadowColourId , Colour(0x00000000));
   preset.setText(
      "Preset 12\n"
   );
   preset.moveCaretToTop(false);
   preset.setCaretVisible(false);
   preset.setReadOnly(true);
   preset.setScrollbarsShown(false);
   preset.setIndents(0, 0);
   preset.setLineSpacing(1.20000008174351f);
   preset.setMultiLine(true, false);
}

void PresetMenu::initializePaths() {
   // Path initialization for fill
   Path fillPath;
   fillPath.startNewSubPath(Point<float>(202.0f, 25.0f));
   fillPath.cubicTo(
      Point<float>(202.0f, 25.0f),
      Point<float>(0.0f, 25.0f),
      Point<float>(0.0f, 25.0f)
   );
   fillPath.cubicTo(
      Point<float>(0.0f, 25.0f),
      Point<float>(0.0f, 0.0f),
      Point<float>(0.0f, 0.0f)
   );
   fillPath.cubicTo(
      Point<float>(0.0f, 0.0f),
      Point<float>(202.0f, 0.0f),
      Point<float>(202.0f, 0.0f)
   );
   fillPath.cubicTo(
      Point<float>(202.0f, 0.0f),
      Point<float>(202.0f, 25.0f),
      Point<float>(202.0f, 25.0f)
   );
   fillPath.closeSubPath();
   const PathStrokeType fillStroke (1.0f, PathStrokeType::JointStyle::mitered, PathStrokeType::EndCapStyle::butt);
   const FillType fillFill (Colour(0xff5b5b5b));
   const FillType fillStrokeFill (Colour(0x00000000));
   fill.setPath(fillPath);
   fill.setStrokeType(fillStroke);
   fill.setFill(fillFill);
   fill.setStrokeFill(fillStrokeFill);
}
