/*
==============================================================================

  This file was auto-generated by the GINnJUCE Transpiler. You're welcome!

==============================================================================
*/

#ifndef PRESETMENU_H_INCLUDED
#define PRESETMENU_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"

class PresetMenu :
public Component
{
public:
   PresetMenu();
   ~PresetMenu();

   void paint(Graphics&) override;
   void resized() override;

   void initializeText();
   void initializePaths();

private:
   TextEditor preset;
   DrawablePath fill;
   
   JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (PresetMenu)
};

#endif // PRESETMENU_H_INCLUDED
